// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQ7qwgUxX17Ax43HD08wZ2XnmI88MG_o',
    appId: '1:601363258021:web:972f1a04adf86b567ccb4c',
    messagingSenderId: '601363258021',
    projectId: 'bookclubrestauracao',
    authDomain: 'bookclubrestauracao.firebaseapp.com',
    storageBucket: 'bookclubrestauracao.firebasestorage.app',
    measurementId: 'G-B18L91BZ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvr0l05ADokTztaKpz3ruZ8eUtXn1p4mo',
    appId: '1:601363258021:android:72f63d69fdc21cd27ccb4c',
    messagingSenderId: '601363258021',
    projectId: 'bookclubrestauracao',
    storageBucket: 'bookclubrestauracao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3iMWzHkSEFtKrJ9RtZQJ318R-P2UI0Iw',
    appId: '1:601363258021:ios:081ee404c3ab20077ccb4c',
    messagingSenderId: '601363258021',
    projectId: 'bookclubrestauracao',
    storageBucket: 'bookclubrestauracao.firebasestorage.app',
    iosBundleId: 'com.example.bookClubRestauracao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3iMWzHkSEFtKrJ9RtZQJ318R-P2UI0Iw',
    appId: '1:601363258021:ios:081ee404c3ab20077ccb4c',
    messagingSenderId: '601363258021',
    projectId: 'bookclubrestauracao',
    storageBucket: 'bookclubrestauracao.firebasestorage.app',
    iosBundleId: 'com.example.bookClubRestauracao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYQ7qwgUxX17Ax43HD08wZ2XnmI88MG_o',
    appId: '1:601363258021:web:eb5e51bcde0a3d777ccb4c',
    messagingSenderId: '601363258021',
    projectId: 'bookclubrestauracao',
    authDomain: 'bookclubrestauracao.firebaseapp.com',
    storageBucket: 'bookclubrestauracao.firebasestorage.app',
    measurementId: 'G-2J2G02D2VL',
  );
}
